"""
Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

limit = 4000000

def generate_fibonacci(fibonacci):
    fibonacci.append(sum(fibonacci[-2:]))

    if fibonacci[-1] < limit:
        generate_fibonacci(fibonacci)
    else:
        fibonacci.pop()

if __name__ == '__main__':
    fibonacci = [1, 2]
    generate_fibonacci(fibonacci)
    s = sum([i for i in fibonacci if i%2==0])
    # print(fibonacci)
    print(s)
